kind: Service
apiVersion: v1
metadata:
  name: spring-app
  labels:
    app: spring-app
    app.kubernetes.io/component: spring-app
    app.kubernetes.io/instance: spring-app
spec:
  clusterIP: 172.30.46.192
  ipFamilies:
    - IPv4
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: 8443-tcp
      protocol: TCP
      port: 8443
      targetPort: 8443
    - name: 8778-tcp
      protocol: TCP
      port: 8778
      targetPort: 8778
  internalTrafficPolicy: Cluster
  clusterIPs:
    - 172.30.46.192
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    deployment: spring-app